<article class="forum">
    <?php if (isset($queryFields['state']) && $queryFields['state'] === 'false') :?>
        <p>le commentaire est vide</p>
    <?php endif ?>
    <h2>Sujet: <?= htmlspecialchars($article['subject']) ?></h2>
    <div class="discussion">
        <div>
            <img class="user" src="<?=$wwwUrl ?>/img/maquette/user.png" width="100" height="100" alt="title" title="title">
            <p><?= htmlspecialchars($article['name']) ?></p>
            <p><?= htmlspecialchars($article['createdAt']) ?></p>
            <?php if ($article['user_id'] === $userSession->getUserId() || $userSession->isAdmin()) :?>
                <a href="<?= $requestUrl ?>/forum/newSubject?update&id=<?= htmlspecialchars($article['id']) ?>"><i class="fa fa-wrench"></i>&eacute;diter</a>
                <a href="<?= $requestUrl ?>/forum/newSubject?delete&id=<?= htmlspecialchars($article['id']) ?>"><i class="fa fa-trash"></i>Supprimer</a>
            <?php endif ?>
        </div>
        <div>
            <?= $GLOBALS['purifier']->purify($article['content']) ?>
        </div>
    </div>
</article>
<article class="forum comment">
    <h2>Commentaire</h2>
        <?php foreach ($comments AS $comment) :?>
            <div class="comment">
                <div>
                    <img class="user" src="<?=$wwwUrl ?>/img/maquette/user.png" width="100" height="100" alt="title" title="title">
                    <p><?= htmlspecialchars($comment['name']) ?></p>
                    <p><?= htmlspecialchars($comment['createdAt']) ?></p>
                    <?php if ($comment['user_id'] === $userSession->getUserId() || $userSession->isAdmin()) :?>
                        <p><a href="<?= $requestUrl ?>/forum/article?delete&id=<?= htmlspecialchars($comment['id']) ?>&idArticle=<?= $queryFields['id'] ?>&user_id=<?= $comment['user_id'] ?>"><i class="fa fa-trash"></i>Supprimer</a></p>
                    <?php endif ?>
                </div>
                <div>
                    <p><?= $GLOBALS['purifier']->purify($comment['content']) ?></p>
                </div>
            </div>
        <?php endforeach ?>
    <form action="<?= $requestUrl ?>/forum/article?id=<?= $queryFields['id'] ?>" method="post">
        <h3>Réponse</h3>
        <div>
            <textarea id="editor" name="comment"></textarea>
        </div>
        <input type="submit" value="Envoyer">
    </form>
</article>
<script src="<?= $wwwUrl ?>/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>