<?php ob_start() ?>
<h2 class="admin">Tableau de bord</h2>
<form class="insertArticle" action="index.php?action=<?= (isset($_GET['updatePost'])) ? 'updatePost' : 'insert' ?>" method="post">
    <fieldset>
        <legend><i class="fa fa-pencil"></i> Nouvel article</legend>
        <input type="hidden" name="id" value="<?= (isset($_GET['id'])) ? htmlspecialchars($onePost['id']) : false ?>">
        <div>
            <label for="title">Titre</label>
            <input id="title" type="text" name="title" value="<?= (isset($_GET['id'])) ? htmlspecialchars($onePost['title']) : false ?>">
        </div>
        <div>
            <label for="content">Contenu</label>
            <textarea id="editor" name="content"><?= (isset($_GET['id'])) ? $this->purifier->purify($onePost['content']) : false ?></textarea>
        </div>
        <div>
            <label for="author">Autheur</label>
            <select id="author" name="author">
                <?php if (isset($_GET['idAuthor'])) :?>
                    <option value="<?= htmlspecialchars($oneAuthor['id']) ?>" selected ><?= htmlspecialchars($oneAuthor['firstName']) ?> <?= htmlspecialchars($oneAuthor['lastName']) ?></option>
                <?php endif ?>
                <?php foreach ($authors as $author): ?>
                    <option value="<?= htmlspecialchars($author['id']) ?>"><?= htmlspecialchars($author['firstName']) ?> <?= htmlspecialchars($author['lastName']) ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <input type="submit" value="Poster">
    </fieldset>
</form>
    <fieldset class="formAuthor">
        <form action="index.php?action=insertAuthor" method="post">
            <fieldset>
                <legend><i class="fa fa-pencil"></i> Nouvel auteur</legend>
                <div>
                    <label for="firstName">Prénom</label>
                    <input id="firstName" type="text" name="firstName">
                </div>
                <div>
                    <label for="lastName">Nom</label>
                    <input id="lastName" type="text" name="lastName">
                </div>
                <input type="submit" value="Ajouter">
            </fieldset>
        </form>
        <form action="index.php?action=deleteAuthor" method="post">
            <fieldset>
                <legend><i class="fa fa-trash"></i> Supprimer auteur</legend>
                <label for="author">Auteur</label>
                <div>
                    <select id="auhtor" name="author">
                        <?php foreach ($authors as $author): ?>
                            <option value="<?= htmlspecialchars($author['id']) ?>"><?= htmlspecialchars($author['firstName']) ?> <?= htmlspecialchars($author['lastName']) ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <input type="submit" value="Supprimer">
            </fieldset>
        </form>
    </fieldset>

<article class="comments">
    <h2>Liste des articles</h2>
    <table class="listAdmin">
        <thead>
            <tr>
                <th>Action</th>
                <th>Titre</th>
                <th>Contenu</th>
                <th>Auteur</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($result as $item) :?>
                <tr>
                    <td><a href="index.php?action=delete&id=<?= htmlspecialchars($item['id']) ?>"><i class="fa fa-trash fa-2x"></i></a>
                        <a href="index.php?action=change&id=<?= htmlspecialchars($item['id']) ?>&idAuthor=<?= htmlspecialchars($item['author_id']) ?>&updatePost"><i class="fa fa-edit fa-2x"></i></a></td>
                    <td><a href="index.php?action=adminAllComments&id=<?= htmlspecialchars($item['id']) ?>"><?= htmlspecialchars($item['title']) ?></a></td>
                    <td><?= substr($this->purifier->purify($item['content']), 0, 200) ?> [...]</td>
                    <td><?= htmlspecialchars($item['firstName']) ?><br><?= htmlspecialchars($item['lastName']) ?></td>
                    <td><?= htmlspecialchars($item['createdAt']) ?></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</article>
<?php $content = ob_get_clean();
require 'view/layoutView.phtml';