<section class="parcours">
    <h2>&Eacute;cole 3w Academy</h2>
    <a href="https://3wa.fr" target="_blank">https://3wa.fr</a>
    <p>C'est dans cette école où j'ai pu suivre une formation développeur web en 3 mois qui m'a permis d'acquérir des bases solides sur cinq technologies:</p>
    <ul>
        <li><a href="<?= $requestUrl ?>/myPath/html"><img src="<?=$wwwUrl ?>/img/languages/html5.png" alt="logo html" title="logo html" height="50" width="50"></a></i></li>
        <li><a href="<?= $requestUrl ?>/myPath/css"><img src="<?=$wwwUrl ?>/img/languages/css3.png" alt="logo css" title="logo css" height="50" width="50"></a></i></li>
        <li><a href="<?= $requestUrl ?>/myPath/js"><img src="<?=$wwwUrl ?>/img/languages/javascript.png" alt="logo javascript" title="logo javascript" height="50" width="50"></a></i></li>
        <li><a href="<?= $requestUrl ?>/myPath/php"><img src="<?=$wwwUrl ?>/img/languages/php.png" alt="logo php" title="logo php" height="50" width="50"></a></i></li>
        <li><a href="<?= $requestUrl ?>/myPath/sql"><img src="<?=$wwwUrl ?>/img/languages/mysql.png" alt="logo mysql" title="logo mysql" height="50" width="50"></a></i></li>
    </ul>
    <p>Au cours de cette formation j'ai travaillé sur des projets, des applications de tout genre, avec d'excellents professeurs !</p>
    <h3>Exemple de maquettes de sites que j'ai réalisées</h3>
    <div class="maquettes">
        <a href="<?=$wwwUrl ?>/img/maquette/wolf.png"><img src="<?=$wwwUrl ?>/img/maquette/wolf.png" height="500" width="300"  title="maquette du site" alt="maquette du site"></a>
        <a href="<?=$wwwUrl ?>/img/maquette/boostrap.png"><img src="<?=$wwwUrl ?>/img/maquette/boostrap.png" height="500" width="300"  title="maquette du site" alt="maquette du site"></a>
        <a href="<?=$wwwUrl ?>/img/maquette/cupoftea.jpg"><img src="<?=$wwwUrl ?>/img/maquette/cupoftea.jpg" height="500" width="300"  title="maquette du site" alt="maquette du site"></a>
        <a href="<?=$wwwUrl ?>/img/maquette/johndoe.jpg"><img src="<?=$wwwUrl ?>/img/maquette/johndoe.jpg" height="500" width="300"  title="maquette du site" alt="maquette du site"></a>
    </div>
</section>
<section class="impression">
    <h3>Mes impressions sur la formation</h3>
    <p>Tout d'abord sachez que ce type de formation accélerée en seulement 3 mois est un parcours où l'on apprend à apprendre.
    L'idée est d'être formé rapidement sur ces 5 langages à raison de 35h par semaine 5jours/7.<br>
    90% pratique 10% théorie: vous l'aurez compris c'est extrèmement intense ! D'entrée de jeu, vous allez vous mettre à coder.
    Durant ces 3 mois le temps passe très vite, et l'on se retrouve rapidement le jour de l'examen !<br>
    Pour ma part cette reconversion ne s'est pas faite en un claquement de doigt et de partir d'un niveau <strong>0</strong> a été très brutal mais très intéressant et enrichissant.
    Le plus dur pour moi a été de ne pas lâcher prise ! J'ai eu des moments de blues ou je me remettais en question:
    "pourquoi suis-je ici ? Est-ce fait pour moi ? dois-je abandonner ? c'est trop dur..."<br>
    Personnelement et je pense que pour beaucoup de personnes nous nous heurtons à des phases de découragement. Je vous assure qu'avec du recul,
    il faut une grande volonté, de l'adaptabilité et surtout de la motivation.Vous parviendrez ainsi à vous surpasser, à prendre confiance et développer deviendra un réel plaisir.
    Aujourd'hui je suis fière d'avoir fait ce choix car maintenant j'ai enfin trouvé ma voie, une nouvelle passion !
    J'encourage fortement ceux et celles qui ont le goût du challenge, de la créativité, de se lancer dans ce métier du numérique passionnant !
    Vous serez récompensé de tous vos efforts, et vos connaissances doivent être quodiennement mises à jour
    pour faire face à un monde ultra connecté.</p>
</section>
<section class="diploma">
    <h3>Diplôme obtenu</h3>
    <div>
        <img src="<?=$wwwUrl ?>/mypath/diplome/rncp.jpg" width="1000" height="800" title="diplôme rncp" alt="diplôme rncp">
    </div>
</section>