<section class="home">
    <h2><i class="fa fa-code" aria-hidden="true"></i> Bienvenue sur mon site <i class="fa fa-code" aria-hidden="true"></i></h2>
    <div class="diapo">
        <img class="slider" src="" alt="photo de développeur" title="photo de développeur" width="400" height="250">
    </div>
    <p>Jeune développeur et intégrateur web, je me suis reconverti vers un métier plus prometteur et novateur,
    ayant suivi une formation intense je vous fais part de mon expérience et ainsi ma toute nouvelle passion !</p>
</section>
