<article class="language">
    <h2>Le langage SQL</h2>
    <p>Le SQL (Structured Query Language) est un langage permettant de communiquer avec une base de données.
    Ce langage informatique est notamment très utilisé par les développeurs web pour communiquer
    avec les données d’un site web. Les principales commandes de ce langage sont: lire, insérer, modifier et
    supprimer des données dans une base. Beaucoup de systèmes utilisent une gestion de bases de données
    comme: MySQL, PostgreSQL, SQL Server ou encore Oracle.</p>
    <p>Pour ma part, j'ai étudié MySql en utilisant une interface nommée phpMyAdmin qui permet de faire des requêtes sql.
    Il a été conçu en php et offre une belle interface. En tant que débutant, je recommande fortement de commencer par là.
    Vous pouver ajouter des tables, en supprimer, modifier directement sans taper le code source !
    il sera même fourni lors des opérations ! C'est un bon moyen d'apprendre et de comprendre comment cela
    marche.</p>
    <p>Le code source s'intégre très bien dans un script php afin de manipuler les données du site.<br>
    Pour vous donner une image de ce que cela représente, si vous connaissez Excel, les bases de données sont assez
    semblables.</p>
    <img src="<?= $wwwUrl ?>/img/languages/bdd.png">
    <p>Voici une table de base de données.</p>
    <p>Lors de l'apprentissage, j'ai eu un plus de facilité à prendre en main son fonctionnement. Cependant construire
    une base de données demande de la réflexion car il faut se poser la question des différentes relations entre les table.
    Si je supprime une table alors y aura-t-il des répercussions sur l'autre table ? Dois-je donc imposer des contraintes etc...
    Cela peut vite devenir un casse-tête. Avec tous ces langages que je viens de citer, vous avez de quoi bâtir un site fonctionnel et complet.
    &Agrave; ce stade il est maintenant judicieux de se pencher sur les frameworks</p>
    <small>extrait du site: http://sql.sh/<br>https://openclassrooms.com/courses/concevez-votre-site-web-avec-php-et-mysql/presentation-des-bases-de-donnees-2</small>
</article>