<article class="myGames">
    <h3>Le Snake</h3>
    <div class="game">
        <div>
            <a href="../../app_externe/snake" target="_blank"><img src="<?= $wwwUrl ?>/img/appli_externe/fond.png" width="700" height="400" alt="snake" title="snake"></a>
        </div>
        <div>
            <p>Le grand classique ! le serpent doit manger la pomme sans se prendre un mur ou se manger lui-même !<br>
            manger un maximum de pommes pour gagner des points.</p>
            <p>Développé en javascript.<br>
            le plus délicat à été de trouver le bon algorithme pour que le serpent puisse bien suivre les virages quand il prend de l'ampleur.<br>
            Le reste ne relève sans trop de difficultés et très agréable à développer.</p>
        </div>
    </div>
    <h3>Le Memory</h3>
    <div class="game">
        <div>
            <a href="../../app_externe/memory" target="_blank"><img src="<?= $wwwUrl ?>/img/appli_externe/fondMemory.png" width="700" height="400" alt="memory" title="memory"></a>
        </div>
        <div>
            <p>Un jeu d'adresse très connu. Trouvez les paires le plus vite possible</p>
            <p>Développé en javascript.<br>Il se développe rapidement mais demande une rigourosité dans le code,
            car on peut vite se mêler les pinceaux ! Il faut donc bien décortiquer les fonctions</p>
        </div>
    </div>
    <h3>Le blackJack</h3>
    <div class="game">
        <div>
            <a href="../../app_externe/blackjack" target="_blank"><img src="<?= $wwwUrl ?>/img/appli_externe/fondblackjack.png" width="700" height="400" alt="blackjack" title="blackjack"></a>
        </div>
        <div>
            <p>Mon tout premier jeu que j'ai conçu. Un super exercice à faire car il y a de tout<br>
            des boucles, des conditions, utilisation de la fonction random. le plus dur à été de penser à tous les cas de figures possible
            car il y en a beaucoup autant que les règles du blackjack.</p>
            <p>Développé en javascript.<br>J'ai essayé de me rapprocher de la version original. Il y a la règle du "split" que je n'ai pas voulu intégrer
            où le joueur a la possibilité de diviser son jeu quand il a une pair en début de partie. Je ne trouvais pas cette règle spécialement nécessaire.<br>
            Le but est de gagner le croupier jusqu'à qu'il n'ai plus d'argent.</p>
        </div>
    </div>
</article>

