<article class="language">
    <h2>Le langage HTML5</h2>
    <p>Initiale: HyperText Markup Language</p>
    <p>Le html est un langage de balise "&#60;/&#62;" indispensable pour concevoir des sites internet,
    il est simple et se maitrise assez vite.<br>
    Pour ma part quelque soit votre niveau il est accessible à tous, pour débuter dans ce métier je vous
    recommande de commencer par cette étape-la</p>
    <p>Le HTML5 (5ème version) est un langage inspiré du XML et qui repose sur le principe de balises imbriquées.
    En résumé, il sert à indiquer au navigateur (internet explorer, firefox, safari …)
    comment afficher la page web.</p>
    <p>Exemple pour afficher un simple "welcome":<br>&#60;p&#62;Welcome&#60;/p&#62;</p>
    <p>Il existe de nombreuses balises (titre, paragraphe, liste, insertion d'image/vidéo, lien...)
    qui respectent une utilisation logique dans la structure de notre site,
    il est le squelette.</p>
    <p>Au cours de la formation ce langage ne m'a pas posé de souci. Cependant il y une convention
    très importante à respecter: l'indentation.<br>Exemple de code html avec une indentation propre:</p>
    <img src="<?=$wwwUrl ?>/img/languages/indentation.png" height="342" width="694"  title="indentation de code" alt="indentation de code">
    <p>On peut remarquer que dans les balises html head et body, il y a une tabulation ! C'est le
    principe de l'indentation permettant de respecter la hiérarchie. Sur l'exemple, on peut tout
    mettre en une seule ligne. Le navigateur interprétra sans problème. Mais pour des raisons évidentes,
    il est bien plus joli de présenter de cette façon. Cela sera plus compréhensible pour les autres développeurs
    quand ils liront ce code.
    Enfin, il existe un validateur de code html en ligne qui analyse le code afin de trouver d'éventuelles erreurs.<br>
    <a href="https://validator.w3.org/#validate_by_input" target="_blank">https://validator.w3.org/#validate_by_input</a></p>
    <p>En résumé, le html vous donne un avant-goût de ce que vous réserve le développement web.
    Petite précision: le html fais parti du domaine de l'intégration au même titre que le langage
    <a href="<?= $requestUrl ?>/myPath/css">css</a></p>
    <small>extrait utilisé du site: http://41mag.fr/a-quoi-sert-le-html5-que-peut-on-faire-avec-quels-sont-ses-limites.html</small>
</article>