<article class="language">
    <h2>Le language Javascript</h2>
    <p>JavaScript est un langage de programmation de scripts orienté objet principalement employé dans
    les pages web interactives.<br>
    La particularité du JavaScript consiste à créer des petits scripts sur une page HTML
    dans le but d'ajouter une petite animation ou un effet particulier sur la page.
    Cela permet en général d'améliorer l'ergonomie ou l'interface utilisateur, mais
    certains scripts sont peu utiles et servent surtout à ajouter un effet esthétique à
    la page. L'intérêt du JavaScript est d'exécuter un code sans avoir à recharger une
    nouvelle fois la page.
    JavaScript est un langage dit client-side, c'est-à-dire interprété par le client (le navigateur).</p>
    <p>Javascript nous permet donc d'interagir avec l'utilisateur grâce à son moteur de recherche
    comme chrome, firefox ou internet explorer. Ces interactions avec l'utilisateur peuvent
    être par exemple :</p>
    <ul>
        <li>Afficher/masquer du texte.</li>
        <li>Faire défiler des images.</li>
        <li>Créer un diaporama avec un aperçu « en grand » des images.</li>
        <li>Créer des infobulles.</li>
    </ul>
    <p>Contrairement au html et css, javascript est un langage de développement. Il s'agit donc
    de programmation pure car on parle de <strong>variable.</strong><br>
    Une variable est un objet repérée par son nom, pouvant contenir
    des données, qui pourront être modifiées lors de l'exécution du programme.<br>
    Au fil du temps, javascript cesse d'évoluer et permet aussi d'être exécuté sur n'importe quelle
    machine. Quelques projets permettant d'utiliser le JavaScript en dehors de votre navigateur,
    le projet le plus connu est sans doute Node.js.</p>
    <p>&Agrave; présent j'aimerais vous montrer une application tout en javascript orientée objet que j'ai réalisée pendant
    ma formation: l'ardoise magique !</p>
    <a href="../../app_externe/Ardoise/index.html" target="_blank"><img src="<?= $wwwUrl ?>/img/appli_externe/ardoise" width="900" height="600" alt="ardoise" title="ardoise"></a>
    <p>Un exercice qui n'était pas évident du tout car c'était une grande première dans la
    programmation orientée objet. Jusqu'a présent, je codais en procédurale. On va dire
    que c'est une manière de programmer à l'ancienne sans avoir une structure précise alors qu'avec
    la programmation orienté objet on a une organisation beaucoup plus structurelle et bien plus compréhensible !
    Sachez qu'un code doit être apte à évoluer sans problème et rapidement, et donc de cette
    manière c'est pour moi la meilleure des options.</p>
    <p>Pour résumer je dirais que javascript a été compliqué pour moi au début... dans la programmation
    que ce soit javascript, <a href="<?= $requestUrl ?>/myPath/php">php</a> ou autre chose, il y a une logique à comprendre. Certaines
    personnes l'acquièrent rapidement. Pour d'autres comme moi, où il faut beaucoup plus de temps
    et plus de travail.</p>
    <small>extrait du site: http://glossaire.infowebmaster.fr/javascript/
    <br>https://openclassrooms.com/courses/dynamisez-vos-sites-web-avec-javascript/introduction-au-javascript</small>
</article>