<?php if (!isset($queryFields['changePasswordTo'])): ?>
    <form class="changePassword" action="<?= $requestUrl ?>/registration/user/updatepassword" method="post">
        <fieldset>
            <div>
                <label for="email">Votre adresse mail</label>
                <input id="email" type="text" name="email">
            </div>
            <input type="submit" value="Envoyer">
        </fieldset>
    </form>
    <?php if (isset($queryFields['state']) && $queryFields['state'] === 'noexist'): ?>
        <p class="errorChangePassword">L'adresse mail ne figure pas dans les comptes enregistrés</p>
    <?php endif ?>
<?php else: ?>
    <form class="changePassword" action="<?= $requestUrl ?>/registration/user/updatepassword" method="post">
        <fieldset>
            <div>
                <label for="password">Votre nouveau mot de passe</label>
                <input id="password" type="password" name="password">
            </div>
            <div>
                <label for="confirmPassword">Confirmation de votre nouveau mot de passe</label>
                <input id="confirmPassword" type="password" name="confirmPassword">
            </div>
            <input type="hidden" value="<?= $queryFields['changePasswordTo'] ?>" name="changePasswordTo">
            <input type="hidden" value="<?= $queryFields['key'] ?>" name="key">
            <input type="submit" value="Envoyer">
        </fieldset>
    </form>
    <?php if (isset($queryFields['state'])): ?>
        <?php if ($queryFields['state'] === 'length'): ?>
            <p class="errorChangePassword">Le mots de passe doit avoir au minimum 4 caractères</p>
        <?php else: ?>
            <p class="errorChangePassword">Les mots de passes ne sont pas identiques</p>
        <?php endif ?>
    <?php endif ?>
<?php endif ?>

